// Generated by scripts/languages.mjs from ICU 78.2: do not edit.

/** A language, and region, dates, times and numbers are written in: named in English and itself. */
export interface LocaleName {
  tag: string;
  english: string;
  native: string;
}

export const LANGUAGES: readonly LocaleName[] = [
  {
    tag: 'ar-AE',
    english: 'Arabic (United Arab Emirates)',
    native: 'العربية (الإمارات العربية المتحدة)',
  },
  {
    tag: 'ar-EG',
    english: 'Arabic (Egypt)',
    native: 'العربية (مصر)',
  },
  {
    tag: 'ar-JO',
    english: 'Arabic (Jordan)',
    native: 'العربية (الأردن)',
  },
  {
    tag: 'ar-MA',
    english: 'Arabic (Morocco)',
    native: 'العربية (المغرب)',
  },
  {
    tag: 'ar-SA',
    english: 'Arabic (Saudi Arabia)',
    native: 'العربية (المملكة العربية السعودية)',
  },
  {
    tag: 'bn-BD',
    english: 'Bangla (Bangladesh)',
    native: 'বাংলা (বাংলাদেশ)',
  },
  {
    tag: 'cs-CZ',
    english: 'Czech (Czechia)',
    native: 'čeština (Česko)',
  },
  {
    tag: 'da-DK',
    english: 'Danish (Denmark)',
    native: 'dansk (Danmark)',
  },
  {
    tag: 'de-AT',
    english: 'Austrian German',
    native: 'Österreichisches Deutsch',
  },
  {
    tag: 'de-CH',
    english: 'Swiss High German',
    native: 'Schweizer Hochdeutsch',
  },
  {
    tag: 'de-DE',
    english: 'German (Germany)',
    native: 'Deutsch (Deutschland)',
  },
  {
    tag: 'el-GR',
    english: 'Greek (Greece)',
    native: 'Ελληνικά (Ελλάδα)',
  },
  {
    tag: 'en-AU',
    english: 'Australian English',
    native: 'Australian English',
  },
  {
    tag: 'en-CA',
    english: 'Canadian English',
    native: 'Canadian English',
  },
  {
    tag: 'en-GB',
    english: 'British English',
    native: 'British English',
  },
  {
    tag: 'en-IE',
    english: 'English (Ireland)',
    native: 'English (Ireland)',
  },
  {
    tag: 'en-IN',
    english: 'English (India)',
    native: 'English (India)',
  },
  {
    tag: 'en-NG',
    english: 'English (Nigeria)',
    native: 'English (Nigeria)',
  },
  {
    tag: 'en-NZ',
    english: 'English (New Zealand)',
    native: 'English (New Zealand)',
  },
  {
    tag: 'en-US',
    english: 'American English',
    native: 'American English',
  },
  {
    tag: 'en-ZA',
    english: 'English (South Africa)',
    native: 'English (South Africa)',
  },
  {
    tag: 'es-AR',
    english: 'Spanish (Argentina)',
    native: 'español (Argentina)',
  },
  {
    tag: 'es-ES',
    english: 'European Spanish',
    native: 'español de España',
  },
  {
    tag: 'es-MX',
    english: 'Mexican Spanish',
    native: 'español de México',
  },
  {
    tag: 'fa-IR',
    english: 'Persian (Iran)',
    native: 'فارسی (ایران)',
  },
  {
    tag: 'fi-FI',
    english: 'Finnish (Finland)',
    native: 'suomi (Suomi)',
  },
  {
    tag: 'fil-PH',
    english: 'Filipino (Philippines)',
    native: 'Filipino (Pilipinas)',
  },
  {
    tag: 'fr-BE',
    english: 'French (Belgium)',
    native: 'français (Belgique)',
  },
  {
    tag: 'fr-CA',
    english: 'Canadian French',
    native: 'français canadien',
  },
  {
    tag: 'fr-CH',
    english: 'Swiss French',
    native: 'français suisse',
  },
  {
    tag: 'fr-FR',
    english: 'French (France)',
    native: 'français (France)',
  },
  {
    tag: 'fr-MA',
    english: 'French (Morocco)',
    native: 'français (Maroc)',
  },
  {
    tag: 'he-IL',
    english: 'Hebrew (Israel)',
    native: 'עברית (ישראל)',
  },
  {
    tag: 'hi-IN',
    english: 'Hindi (India)',
    native: 'हिन्दी (भारत)',
  },
  {
    tag: 'hu-HU',
    english: 'Hungarian (Hungary)',
    native: 'magyar (Magyarország)',
  },
  {
    tag: 'id-ID',
    english: 'Indonesian (Indonesia)',
    native: 'Indonesia (Indonesia)',
  },
  {
    tag: 'it-IT',
    english: 'Italian (Italy)',
    native: 'italiano (Italia)',
  },
  {
    tag: 'ja-JP',
    english: 'Japanese (Japan)',
    native: '日本語 (日本)',
  },
  {
    tag: 'ko-KR',
    english: 'Korean (South Korea)',
    native: '한국어(대한민국)',
  },
  {
    tag: 'ms-MY',
    english: 'Malay (Malaysia)',
    native: 'Melayu (Malaysia)',
  },
  {
    tag: 'nb-NO',
    english: 'Norwegian Bokmål (Norway)',
    native: 'norsk bokmål (Norge)',
  },
  {
    tag: 'nl-BE',
    english: 'Flemish',
    native: 'Vlaams',
  },
  {
    tag: 'nl-NL',
    english: 'Dutch (Netherlands)',
    native: 'Nederlands (Nederland)',
  },
  {
    tag: 'pl-PL',
    english: 'Polish (Poland)',
    native: 'polski (Polska)',
  },
  {
    tag: 'pt-BR',
    english: 'Brazilian Portuguese',
    native: 'português (Brasil)',
  },
  {
    tag: 'pt-PT',
    english: 'European Portuguese',
    native: 'português europeu',
  },
  {
    tag: 'ro-RO',
    english: 'Romanian (Romania)',
    native: 'română (România)',
  },
  {
    tag: 'ru-RU',
    english: 'Russian (Russia)',
    native: 'русский (Россия)',
  },
  {
    tag: 'sv-SE',
    english: 'Swedish (Sweden)',
    native: 'svenska (Sverige)',
  },
  {
    tag: 'sw-KE',
    english: 'Swahili (Kenya)',
    native: 'Kiswahili (Kenya)',
  },
  {
    tag: 'th-TH',
    english: 'Thai (Thailand)',
    native: 'ไทย (ไทย)',
  },
  {
    tag: 'tr-TR',
    english: 'Turkish (Türkiye)',
    native: 'Türkçe (Türkiye)',
  },
  {
    tag: 'uk-UA',
    english: 'Ukrainian (Ukraine)',
    native: 'українська (Україна)',
  },
  {
    tag: 'ur-PK',
    english: 'Urdu (Pakistan)',
    native: 'اردو (پاکستان)',
  },
  {
    tag: 'vi-VN',
    english: 'Vietnamese (Vietnam)',
    native: 'Tiếng Việt (Việt Nam)',
  },
  {
    tag: 'zh-CN',
    english: 'Chinese (China)',
    native: '中文（中国）',
  },
  {
    tag: 'zh-HK',
    english: 'Chinese (Hong Kong SAR China)',
    native: '中文（中國香港特別行政區）',
  },
  {
    tag: 'zh-TW',
    english: 'Chinese (Taiwan)',
    native: '中文（台灣）',
  },
];
