/** Query keys, in one place so realtime events invalidate exactly what they change. */
export const qk = {
  me: ['me'] as const,
  ai: ['ai'] as const,
  plan: ['plan'] as const,
  billing: ['billing'] as const,
  orgBilling: (orgId: string) => ['org-billing', orgId] as const,
  spaces: ['spaces'] as const,
  orgs: ['orgs'] as const,
  org: (handle: string) => ['org', handle] as const,
  orgInbox: (orgId: string, view: string) => ['org-inbox', orgId, view] as const,
  orgInsights: (orgId: string, days: number) => ['org-insights', orgId, days] as const,
  businessSummary: ['business-summary'] as const,
  tokens: ['personal-tokens'] as const,
  oauthApps: ['oauth-apps'] as const,
  orgAgent: (orgId: string) => ['org-agent', orgId] as const,
  connectedApps: ['connected-apps'] as const,
  space: (id: string) => ['space', id] as const,
  inbox: ['inbox'] as const,
  inboxAll: ['inbox', 'all'] as const,
  conversation: (id: string) => ['conversation', id] as const,
  messages: (id: string) => ['messages', id] as const,
  album: (messageId: string) => ['album', messageId] as const,
  memory: (id: string) => ['memory', id] as const,
  suggestions: (conversationId?: string) => ['suggestions', conversationId ?? 'all'] as const,
  /** Two of someone's connections who may be one person (PRD §51). */
  duplicates: ['suggestions', 'kind', 'duplicate'] as const,
  person: (id: string) => ['person', id] as const,
  /** Call history: every call, the missed ones, or those with one person. */
  calls: (filter: string) => ['calls', filter] as const,
  relationshipHistory: (id: string) => ['relationship-history', id] as const,
  connections: ['connections'] as const,
  /** Updates: the organizations someone follows, and each one's updates (PRD §59). */
  following: ['updates', 'following'] as const,
  orgUpdates: (orgId: string) => ['updates', 'org', orgId] as const,
  requests: (direction: 'incoming' | 'outgoing') => ['requests', direction] as const,
  taxonomy: ['taxonomy'] as const,
  tasks: (view: string, scope?: string) => ['tasks', view, scope ?? ''] as const,
  decisions: (conversationId?: string) => ['decisions', conversationId ?? 'all'] as const,
  notifications: ['notifications'] as const,
  policies: ['policies'] as const,
  sessions: ['sessions'] as const,
  search: (term: string) => ['search', term] as const,
  peopleSearch: (term: string) => ['people-search', term] as const,
};
