// Writes apps/server/src/lib/geo-data.ts from the IANA time zone database installed with tzdata
// (/usr/share/zoneinfo): every country and territory (iso3166.tab), and the country of each time
// zone (zone.tab), old names included (the links in tzdata.zi), since browsers still report some
// (Asia/Calcutta); and from CLDR, each country's currency. Run it again when either changes:
//   npm pack cldr-core && tar -xzf cldr-core-*.tgz package/package.json package/supplemental
//   node scripts/geo.mjs package/supplemental/currencyData.json [zoneinfo dir]
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const cldr = process.argv[2];
if (!cldr) throw new Error('Pass the path of CLDR supplemental/currencyData.json');
const dir = process.argv[3] ?? '/usr/share/zoneinfo';
const lines = (file) =>
  readFileSync(join(dir, file), 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#'));
const version = /^# version (\S+)/m.exec(readFileSync(join(dir, 'tzdata.zi'), 'utf8'))?.[1];
if (!version) throw new Error('No tzdata version found');

const countries = {};
for (const l of lines('iso3166.tab')) {
  const [code, name] = l.split('\t');
  if (/^[A-Z]{2}$/.test(code) && name) countries[code] = name.trim();
}
const zones = {};
for (const l of lines('zone.tab')) {
  const [code, , zone] = l.split('\t');
  if (!countries[code]) throw new Error(`zone.tab names ${code}, which iso3166.tab doesn't`);
  zones[zone] = code;
}
let aliases = 0;
for (const l of readFileSync(join(dir, 'tzdata.zi'), 'utf8').split('\n')) {
  const m = /^L (\S+) (\S+)$/.exec(l);
  if (!m) continue;
  const [, target, alias] = m;
  if (zones[alias] || !zones[target]) continue;
  zones[alias] = zones[target];
  aliases++;
}
// A country's currency: the first it lists that's legal tender and hasn't ended (CLDR lists the
// current one first). None for a territory without one (Antarctica).
const regions = JSON.parse(readFileSync(cldr, 'utf8')).supplemental.currencyData.region;
const cldrVersion = JSON.parse(readFileSync(join(cldr, '../../package.json'), 'utf8')).version;
const currencies = {};
for (const code of Object.keys(countries)) {
  const current = (regions[code] ?? [])
    .map((o) => Object.entries(o)[0])
    .find(([cur, v]) => !v._to && v._tender !== 'false' && /^[A-Z]{3}$/.test(cur) && cur !== 'XXX');
  if (current) currencies[code] = current[0];
}
const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => (a < b ? -1 : 1)));
const out = `// Generated by scripts/geo.mjs from tzdata ${version} and CLDR ${cldrVersion}: do not edit.
// ${Object.keys(countries).length} countries and territories (ISO 3166-1 alpha-2, iso3166.tab), and the
// country of ${Object.keys(zones).length} time zones (zone.tab, and ${aliases} older names of them).

/** Every country and territory, by its ISO 3166-1 code, with its English name. */
export const COUNTRIES: Readonly<Record<string, string>> = ${JSON.stringify(sorted(countries), null, 2)};

/** The country a time zone is in (a zone used across borders names the first, as zone.tab does). */
export const ZONE_COUNTRY: Readonly<Record<string, string>> = ${JSON.stringify(sorted(zones), null, 2)};

/** Each country's currency (ISO 4217), for ${Object.keys(currencies).length} of them (CLDR). */
export const COUNTRY_CURRENCY: Readonly<Record<string, string>> = ${JSON.stringify(sorted(currencies), null, 2)};
`;
writeFileSync(new URL('../apps/server/src/lib/geo-data.ts', import.meta.url), out);
console.log(
  `tzdata ${version}, CLDR ${cldrVersion}: ${Object.keys(countries).length} countries, ${Object.keys(zones).length} zones (${aliases} older names), ${Object.keys(currencies).length} currencies`,
);
