// Writes packages/core/src/languages.ts: the languages (and regions) Caishy writes dates, times
// and numbers in, each named in English and in itself, from this Node's ICU. Run it again when
// the list below changes: node scripts/languages.mjs
import { writeFileSync } from 'node:fs';

const TAGS = [
  'ar-AE',
  'ar-EG',
  'ar-JO',
  'ar-MA',
  'ar-SA',
  'bn-BD',
  'cs-CZ',
  'da-DK',
  'de-AT',
  'de-CH',
  'de-DE',
  'el-GR',
  'en-AU',
  'en-CA',
  'en-GB',
  'en-IE',
  'en-IN',
  'en-NG',
  'en-NZ',
  'en-US',
  'en-ZA',
  'es-AR',
  'es-ES',
  'es-MX',
  'fa-IR',
  'fi-FI',
  'fil-PH',
  'fr-BE',
  'fr-CA',
  'fr-CH',
  'fr-FR',
  'fr-MA',
  'he-IL',
  'hi-IN',
  'hu-HU',
  'id-ID',
  'it-IT',
  'ja-JP',
  'ko-KR',
  'ms-MY',
  'nb-NO',
  'nl-BE',
  'nl-NL',
  'pl-PL',
  'pt-BR',
  'pt-PT',
  'ro-RO',
  'ru-RU',
  'sv-SE',
  'sw-KE',
  'th-TH',
  'tr-TR',
  'uk-UA',
  'ur-PK',
  'vi-VN',
  'zh-CN',
  'zh-HK',
  'zh-TW',
];
const english = new Intl.DisplayNames(['en'], { type: 'language' });
const rows = TAGS.map((tag) => ({
  tag,
  english: english.of(tag),
  native: new Intl.DisplayNames([tag], { type: 'language' }).of(tag),
}));
const out = `// Generated by scripts/languages.mjs from ICU ${process.versions.icu}: do not edit.

/** A language, and region, dates, times and numbers are written in: named in English and itself. */
export interface LocaleName {
  tag: string;
  english: string;
  native: string;
}

export const LANGUAGES: readonly LocaleName[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync(new URL('../packages/core/src/languages.ts', import.meta.url), out);
console.log(`${rows.length} locales, ICU ${process.versions.icu}`);
